export const LOAD_SHUTTLES_REQUEST = 'LOAD_SHUTTLES_REQUEST'
export const LOAD_SHUTTLES_SUCCESS = 'LOAD_SHUTTLES_SUCCESS'
export const LOAD_SHUTTLES_FAIL = 'LOAD_SHUTTLES_FAIL'

export const LOAD_SHUTTLE_REQUEST = 'LOAD_SHUTTLE_REQUEST'
export const LOAD_SHUTTLE_SUCCESS = 'LOAD_SHUTTLE_SUCCESS'
export const LOAD_SHUTTLE_FAIL = 'LOAD_SHUTTLE_FAIL'

export const SAVE_SEATS_DISPATCH = 'SAVE_SEATS_DISPATCH'
export const SAVE_SEATS_SUCCESS = 'SAVE_SEATS_SUCCESS'
export const SAVE_SEATS_FAIL = 'SAVE_SEATS_DISPATCH'

export const SHUTTLE_UPDATE_DISPATCH = 'SHUTTLE_UPDATE_DISPATCH'
export const SHUTTLE_UPDATE_SUCCESS = 'SHUTTLE_UPDATE_SUCCESS'
export const SHUTTLE_UPDATE_FAIL = 'SHUTTLE_UPDATE_DISPATCH'
export const SHUTTLE_UPDATE_RESET = 'SHUTTLE_UPDATE_RESET'

export const SHUTTLE_DELETE_DISPATCH = 'SHUTTLE_DELETE_DISPATCH'
export const SHUTTLE_DELETE_SUCCESS = 'SHUTTLE_DELETE_SUCCESS'
export const SHUTTLE_DELETE_FAIL = 'SHUTTLE_DELETE_DISPATCH'
export const SHUTTLE_DELETE_RESET = 'SHUTTLE_DELETE_RESET'

export const SHUTTLE_ADD_DISPATCH = 'SHUTTLE_ADD_DISPATCH'
export const SHUTTLE_ADD_SUCCESS = 'SHUTTLE_ADD_SUCCESS'
export const SHUTTLE_ADD_FAIL = 'SHUTTLE_ADD_DISPATCH'
export const SHUTTLE_ADD_RESET = 'SHUTTLE_ADD_RESET'